### ISSUE TITLE
Build fails on V 1.0.0. - FileNotFoundError: [Errno 2] No such file or directory: 'bin' during invoke get_requires_for_build_wheel

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [nasa/apod-api#121]
I've got these installed:

BuildRequires:  python3dist(build)
BuildRequires:  python3dist(installer)
BuildRequires:  python3dist(setuptools)
BuildRequires:  python3dist(sphinx)
BuildRequires:  python3dist(wheel)
BuildRequires:  python3dist(pytest)

I'm calling these to build:
pyproject_wheel
pyproject_installer

Error where this fails:

+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/usr/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 39, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'bin'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
error: Bad exit status from /var/tmp/rpm-tmp.SQpjGl (%build)

**Comment by AndreyRojasD** [comment]
Please add the steps to replicate the issue.
